/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cafe.ui.compe;

import java.util.function.Consumer;
import javax.swing.JRadioButton;

/**
 *
 * @author DELL
 */
public class RadioJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RadioGroupJPanel
     */
    public RadioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        imageJPanel1 = new poly.cafe.ui.compe.ImageJPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        group.add(jRadioButton1);
        jRadioButton1.setText("Operating");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);

        group.add(jRadioButton2);
        jRadioButton2.setText("Error");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2);

        group.add(jRadioButton3);
        jRadioButton3.setText("Lose");
        add(jRadioButton3);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group;
    private poly.cafe.ui.compe.ImageJPanel imageJPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables

    JRadioButton[] radios = {};
    private Consumer<Integer> indexChanged;
    
    public void setIndexChanged(Consumer<Integer> indexChanged) {
        this.indexChanged = indexChanged;
        for (JRadioButton radio : radios) {
            radio.addActionListener((e) -> indexChanged.accept(this.getIndex()));
        }
    }

    public void setItems(String[] items) {
        this.removeAll();
        radios = new JRadioButton[items.length];
        for (int i = 0; i < radios.length; i++) {
            radios[i] = new JRadioButton(items[i]);
            this.add(radios[i]);
            group.add(radios[i]);
        }
        this.setIndex(0);
    }

    public int getIndex() {
        if(jRadioButton1.isSelected()){
            return 0; 
        }else if(jRadioButton2.isSelected()){
            return 1; 
        }
        if(jRadioButton3.isSelected()){
            return 2; 
        }
        return 0;
    }
    
    public void setIndex(int index) {
        if(index==0){
            jRadioButton1.setSelected(true); 
        } else if(index==1){
            jRadioButton2.setSelected(true); 
        } else {
            jRadioButton3.setSelected(true); 
        }
//        radios[index].setSelected(true);
    }
    
    public String getText() {
        int index = this.getIndex();
        return radios[index].getText();
    }
}
