/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cafe.ui.compe;

import java.util.function.Consumer;

/**
 *
 * @author DELL
 */
public class SliderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PercentJPanel
     */
    public SliderJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider = new javax.swing.JSlider();
        lblLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        add(slider, java.awt.BorderLayout.CENTER);

        lblLabel.setText("50%");
        add(lblLabel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        lblLabel.setText(String.format("%d%%", slider.getValue()));
        if(this.valueChanged != null){
            this.valueChanged.accept(this.getValue());
        }
    }//GEN-LAST:event_sliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLabel;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
    
    private Consumer<Integer> valueChanged;

    public void setValueChanged(Consumer<Integer> valueChanged) {
        this.valueChanged = valueChanged;
    }
    
    public int getValue() {
        return slider.getValue();
    }

    public void setValue(int value) {
        slider.setValue(value);
    }
}
